<a href="https://colab.research.google.com/github/Faisalmalik01/deeplearning/blob/main/GradientDescent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Cell 1: Import Libraries**
This cell imports necessary libraries for data manipulation, machine learning, and plotting:
- `numpy` (as `np`): For numerical operations.
- `tensorflow` (as `tf`): The deep learning framework.
- `keras`: High-level API for building and training deep learning models (part of TensorFlow).
- `pandas` (as `pd`): For data manipulation and analysis.
- `matplotlib.pyplot` (as `plt`): For creating static, animated, and interactive visualizations.
- `%matplotlib inline`: A magic command for Jupyter/IPython to display plots directly in the notebook output.

In [4]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

### **Cell 2: Load Data and Display Head**
This cell loads the `insurance.csv` dataset into a pandas DataFrame called `df` and then displays the first 5 rows of the DataFrame using `df.head()`. This helps in quickly inspecting the data structure and initial values.

In [5]:
df = pd.read_csv("sample_data/insurance.csv")
df.head()

,age,affordability,bought_insurance
0,22,0,0
1,35,1,1
2,28,0,0
3,45,1,1
4,52,1,1


### **Cell 3: Check DataFrame Shape**
This cell prints the shape of the DataFrame `df`, which indicates the number of rows and columns (e.g., (50, 3) means 50 rows and 3 columns). This is useful for understanding the dataset's dimensions.

In [6]:
df.shape

(50, 3)

### **Cell 4: Split Data into Training and Test Sets**
This cell uses `train_test_split` from `sklearn.model_selection` to divide the dataset into training and testing sets.
- `X` (features) consists of 'age' and 'affordability' columns.
- `y` (target) is the 'bought_insurance' column.
- `test_size=0.2` allocates 20% of the data for testing.
- `random_state=25` ensures reproducibility of the split.

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'affordability']], df.bought_insurance, test_size= 0.2, random_state=25)

### **Cell 5: Check Training Set Length**
This cell simply prints the number of samples (rows) in the training feature set `X_train`. This confirms how many data points are available for model training.

In [8]:
len(X_train)

40

### **Cell 6: Scale 'age' Feature**
This cell creates copies of the training and testing feature sets (`X_train_scaled`, `X_test_scaled`) and then scales the 'age' column by dividing it by 100. Feature scaling is often important for neural networks to help with convergence and performance.

In [9]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100

### **Cell 7: Display Scaled Training Data**
This cell displays the `X_train_scaled` DataFrame, allowing you to see the effect of the age scaling.

In [10]:
X_train_scaled

,age,affordability
48,0.61,1
40,0.23,0
2,0.28,0
27,0.39,1
11,0.33,0
6,0.24,0
32,0.56,1
19,0.26,0
29,0.62,1
10,0.48,1


### **Cell 8: Build, Compile, and Train the Keras Model**
This cell defines, compiles, and trains a simple Keras sequential model (a single-layer neural network).
- **Model Definition**: A `Dense` layer with 1 output unit, 2 input features, `sigmoid` activation (suitable for binary classification), `kernel_initializer='ones'`, and `bias_initializer='zeros'`.
- **Model Compilation**: Uses the `adam` optimizer, `binary_crossentropy` loss (standard for binary classification), and tracks `accuracy` as a metric.
- **Model Training**: `model.fit()` trains the model using `X_train_scaled` and `y_train` for 500 `epochs`.

In [11]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=500)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 359ms/step - accuracy: 0.6000 - loss: 0.4772
Epoch 2/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6000 - loss: 0.4767
Epoch 3/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6000 - loss: 0.4764
Epoch 4/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6000 - loss: 0.4761
Epoch 5/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6000 - loss: 0.4757
Epoch 6/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6000 - loss: 0.4753
Epoch 7/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6000 - loss: 0.4750
Epoch 8/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6000 - loss: 0.4746
Epoch 9/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6000 - loss: 0.4742
Epoch 10/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6000 - loss: 0.4738
Epoch 11/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6000 - loss: 0.4735
Epoch 12/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6000 - l

### **Cell 9: Evaluate the Model**
This cell evaluates the trained Keras model on the `X_test_scaled` data and `y_test` labels. It outputs the loss and accuracy of the model on unseen data.

In [12]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - accuracy: 0.9000 - loss: 0.3606


[0.36061006784439087, 0.8999999761581421]

### **Cell 10: Display Scaled Test Data**
This cell displays the `X_test_scaled` DataFrame, which contains the scaled 'age' and 'affordability' features for the test set.

In [13]:
X_test_scaled

,age,affordability
36,0.64,1
46,0.44,1
7,0.40,1
41,0.49,1
17,0.50,1
14,0.42,1
34,0.20,0
33,0.46,1
45,0.33,1
39,0.51,1


### **Cell 11: Make Predictions with the Model**
This cell uses the trained Keras model (`model.predict()`) to generate predictions on the `X_test_scaled` data. The output probabilities indicate the likelihood of buying insurance.

In [14]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step


array([[0.8545636 ],
       [0.83163077],
       [0.8267124 ],
       [0.8376213 ],
       [0.8387986 ],
       [0.8291856 ],
       [0.37830007],
       [0.83404785],
       [0.8178333 ],
       [0.8399689 ]], dtype=float32)

### **Cell 12: Display True Labels for Test Set**
This cell displays the actual 'bought_insurance' labels (`y_test`) for the test set, which can be compared against the model's predictions.

In [15]:
y_test

,bought_insurance
36,1
46,1
7,1
41,1
17,1
14,1
34,0
33,1
45,0
39,1


### **Cell 13: Get Model Weights**
This cell retrieves the `coef` (weights) and `intercept` (bias) from the trained Keras model. These values define the learned linear relationship in the single-layer neural network.

In [16]:
coef, intercept = model.get_weights()
coef, intercept

(array([[0.86811304],
        [1.8856516 ]], dtype=float32),
 array([-0.6703924], dtype=float32))

### **Cell 14: Comment on Scratch Implementation**
This is a markdown cell indicating the intention to implement the neural network from scratch in Python, without using TensorFlow/Keras.

In [17]:
# implementing the same method from scratch in python. (Building a NN from scratch without using TF)

### **Cell 15: Sigmoid Activation Function**
This cell defines a Python function `sigmoid` that calculates the sigmoid activation for a given input `x`. The sigmoid function squashes any real-valued number into a value between 0 and 1, making it suitable for probabilities in binary classification. It then demonstrates its use with an example.

In [18]:
def sigmoid(x):
  import math
  return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

### **Cell 16: Custom Prediction Function**
This cell defines a `prediction_function` that calculates the weighted sum of 'age' and 'affordability' using the `coef` and `intercept` obtained from the Keras model, and then applies the `sigmoid` function. This replicates the forward pass of the Keras model using the learned parameters.

In [19]:
def prediction_function(age, affordability):
  weighted_sum = coef[0]*age + coef[1]*affordability + intercept
  return sigmoid(weighted_sum)

### **Cell 17: Test Custom Prediction Function (Example 1)**
This cell demonstrates the `prediction_function` with `age=0.64` and `affordability=1`, showing the predicted probability of buying insurance. This corresponds to the first entry in `X_test_scaled`.

In [20]:
prediction_function(.64, 1)

/tmp/ipykernel_10108/1956504671.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.8545635305562479

### **Cell 18: Test Custom Prediction Function (Example 2)**
This cell demonstrates the `prediction_function` with `age=0.44` and `affordability=1`, showing another predicted probability. This corresponds to the second entry in `X_test_scaled`.

In [21]:
prediction_function(.44, 1)

/tmp/ipykernel_10108/1956504671.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.8316307271302604

### **Cell 19: Comment on Gradient Descent Implementation**
This is a markdown cell indicating the intention to implement the gradient descent algorithm from scratch in Python.

In [22]:
# implementing GD function in python from scratch

### **Cell 20: Log Loss Function**
This cell defines a `log_loss` function, which is a common loss function for binary classification problems. It incorporates `epsilon` to prevent `log(0)` errors, ensuring numerical stability.

In [23]:
def log_loss(y_true, y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i, epsilon) for i in y_predicted]
  y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

### **Cell 21: NumPy Sigmoid Function**
This cell defines a `sigmoid_numpy` function that applies the sigmoid activation function to a NumPy array, allowing for element-wise operations. It then demonstrates its use with a sample array.

In [24]:
def sigmoid_numpy(X):
  return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12, 0, 1]))

array([0.99999386, 0.5       , 0.73105858])

### **Cell 22: Gradient Descent Implementation**
This cell defines the `gradient_descent` function, which implements the logistic regression algorithm from scratch.
- It initializes weights (`w1`, `w2`) and `bias`.
- It iteratively updates these parameters using the learning `rate` to minimize the `log_loss`.
- The gradients (`w1d`, `w2d`, `bias_d`) are calculated based on the difference between predicted and true values.
- It prints the parameters and loss for each epoch. The loop now includes a `loss_threshold` to stop training early if the loss drops below a certain point.

In [43]:
def gradient_descent(age, affordability, y_true, epochs, loss_threshold):
  # w1, w2, bias
  w1 = w2 = 1
  bias = 0
  rate = 0.5
  n = len(age) #  len of samples

  for i in range(epochs):

    weighted_sum = w1 * age + w2 * affordability + bias

    y_predicted = sigmoid_numpy(weighted_sum)

    loss = log_loss(y_true, y_predicted)

    w1d = (1/n)*np.dot(np.transpose(age), (y_predicted-y_true))
    w2d = (1/n)*np.dot(np.transpose(affordability), (y_predicted-y_true))

    bias_d = np.mean(y_predicted-y_true)

    w1 = w1 - rate * w1d
    w2 = w2 - rate * w2d
    bias = bias - rate * bias_d

    print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

    if loss<=loss_threshold:
      break
  return w1, w2, bias

### **Cell 23: Run Custom Gradient Descent**
This cell calls the `gradient_descent` function with the scaled training data, true labels, a specified number of `epochs` (1000), and a `loss_threshold` (0.3378). It trains the model and prints the updated weights and bias after the training is complete or the loss threshold is met.

In [44]:
gradient_descent(X_train_scaled['age'], X_train_scaled['affordability'], y_train, 1000, 0.3378)


Epoch:0, w1:0.9945110614931334, w2:1.0468713998756745, bias:-0.0592705528275498, loss:0.4772226499220122
Epoch:1, w1:0.9900914659736342, w2:1.0944592844268672, bias:-0.11501809693410606, loss:0.4659234187286998
Epoch:2, w1:0.986598224276006, w2:1.1425398721991247, bias:-0.1676263935567255, loss:0.45529508363845944
Epoch:3, w1:0.9839045522555884, w2:1.1909179591808678, bias:-0.21743777780179452, loss:0.44524748282097193
Epoch:4, w1:0.9818990540620719, w2:1.2394252559213543, bias:-0.2647551564831013, loss:0.4357095420114937
Epoch:5, w1:0.9804845619849775, w2:1.2879181855975808, bias:-0.30984490424195305, loss:0.4266249927025556
Epoch:6, w1:0.9795768042587853, w2:1.3362754274355095, bias:-0.35294021428090555, loss:0.41794892703694797
Epoch:7, w1:0.9791030213407081, w2:1.384395404636908, bias:-0.3942445921016097, loss:0.4096450929611639
Epoch:8, w1:0.9790006106943268, w2:1.4321938480818963, bias:-0.43393528533074166, loss:0.40168380939759263
Epoch:9, w1:0.9792158495581017, w2:1.47960151585

(np.float64(0.9896689236527302),
 np.float64(1.8823826156652443),
 np.float64(-0.7679528897675861))

### **Cell 24: Display Keras Model Weights**
This cell displays the `coef` and `intercept` (weights and bias) that were learned by the Keras model. This is used for comparison with the weights learned by the custom gradient descent implementation.

In [45]:
coef, intercept

(array([[0.86811304],
        [1.8856516 ]], dtype=float32),
 array([-0.6703924], dtype=float32))

### **Cell 25: Manually Set Weights and Bias**
This cell manually sets the `w1`, `w2`, and `bias` variables to specific float values. This is likely done to demonstrate predictions with particular parameter values, or to re-initialize for further experimentation.

In [50]:
w1 = 0.86811304
w2 = 1.8856516
bias = -0.6703924