<a href="https://colab.research.google.com/github/Faisalmalik01/deeplearning/blob/main/implement_NN_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


This cell imports necessary libraries for data manipulation, numerical operations, machine learning (TensorFlow/Keras for building the neural network, scikit-learn for splitting data), and plotting.

In [2]:
df = pd.read_csv("sample_data/insurance.csv")
df.head()

,age,affordability,bought_insurance
0,22,0,0
1,35,1,1
2,28,0,0
3,45,1,1
4,52,1,1


This cell loads the `insurance.csv` dataset into a pandas DataFrame named `df` and displays the first few rows to give a quick overview of the data.

In [3]:
df.shape

(50, 3)

This cell outputs the dimensions (number of rows and columns) of the DataFrame `df`, providing information about the dataset's size.

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'affordability']], df.bought_insurance, test_size= 0.2, random_state=25)

This cell splits the dataset into training and testing sets. `age` and `affordability` are used as features (X), and `bought_insurance` is the target variable (y). A test size of 20% and a `random_state` are set for reproducibility.

In [6]:
len(X_train)

40

This cell displays the number of samples in the training set (`X_train`), which is 40.

In [7]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100

This cell creates scaled versions of the training and testing features. Specifically, the 'age' column is scaled by dividing by 100 to normalize its values, which can improve model performance.

In [8]:
X_train_scaled

,age,affordability
48,0.61,1
40,0.23,0
2,0.28,0
27,0.39,1
11,0.33,0
6,0.24,0
32,0.56,1
19,0.26,0
29,0.62,1
10,0.48,1


This cell displays the `X_train_scaled` DataFrame, showing the normalized 'age' values along with 'affordability'.

In [11]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=500)

Epoch 1/500


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.6000 - loss: 0.4772 
Epoch 2/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6000 - loss: 0.4767
Epoch 3/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6000 - loss: 0.4763
Epoch 4/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6000 - loss: 0.4759
Epoch 5/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6000 - loss: 0.4755
Epoch 6/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6000 - loss: 0.4751
Epoch 7/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6000 - loss: 0.4747
Epoch 8/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6000 - loss: 0.4744
Epoch 9/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6000 - loss: 0.4740
Epoch 10/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6000 - loss: 0.4736
Epoch 11/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6000 - loss: 0.4732 
Epoch 12/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6000 - loss: 0.4728

This cell defines and compiles a simple Keras Sequential model, which is a single-layer neural network with a sigmoid activation function for binary classification. It's then trained on the scaled training data for 500 epochs.

In [12]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - accuracy: 0.9000 - loss: 0.3603


[0.3603147864341736, 0.8999999761581421]

This cell evaluates the trained Keras model on the scaled test data (`X_test_scaled` and `y_test`), reporting the loss and accuracy.

In [13]:
X_test_scaled

,age,affordability
36,0.64,1
46,0.44,1
7,0.40,1
41,0.49,1
17,0.50,1
14,0.42,1
34,0.20,0
33,0.46,1
45,0.33,1
39,0.51,1


This cell displays the `X_test_scaled` DataFrame, which contains the scaled age and affordability features for the test set.

In [14]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[0.85364825],
       [0.83054286],
       [0.8255878 ],
       [0.8365783 ],
       [0.83776444],
       [0.82807946],
       [0.3742465 ],
       [0.83297807],
       [0.8166427 ],
       [0.8389436 ]], dtype=float32)

This cell uses the trained Keras model to make predictions on the `X_test_scaled` data. The output probabilities represent the model's confidence that an individual will buy insurance.

In [15]:
y_test

,bought_insurance
36,1
46,1
7,1
41,1
17,1
14,1
34,0
33,1
45,0
39,1


This cell displays the true labels (`y_test`) for the test set, which can be compared with the model's predictions.

In [16]:
coef, intercept = model.get_weights()
coef, intercept

(array([[0.87013274],
        [1.8946897 ]], dtype=float32),
 array([-0.6880684], dtype=float32))

This cell retrieves the weights (coefficients) and bias from the trained Keras model. These values define the learned linear relationship before the sigmoid activation.

In [17]:
def sigmoid(x):
  import math
  return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

This cell defines a Python function `sigmoid` to compute the sigmoid activation, which squashes any real-valued number into a range between 0 and 1. It also provides a demonstration with an input of 18.

In [18]:
def prediction_function(age, affordability):
  weighted_sum = coef[0]*age + coef[1]*affordability + intercept
  return sigmoid(weighted_sum)

This cell defines a `prediction_function` that mimics the Keras model's prediction logic using the extracted weights and bias, and the custom `sigmoid` function. It takes age and affordability as input and returns the predicted probability.

In [19]:
prediction_function(.64, 1)

/tmp/ipykernel_7543/1956504671.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.8536482401421793

This cell uses the `prediction_function` to make a prediction for an individual with scaled age 0.64 and affordability 1.

In [20]:
prediction_function(.44, 1)

/tmp/ipykernel_7543/1956504671.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.8305428857741641

This cell uses the `prediction_function` to make a prediction for an individual with scaled age 0.44 and affordability 1.

In [22]:
def log_loss(y_true, y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i, epsilon) for i in y_predicted]
  y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

This cell defines a `log_loss` function, which is the binary cross-entropy loss function. It's used to quantify the error between the true labels and the predicted probabilities, with `epsilon` to prevent `log(0)` errors.

In [23]:
def sigmoid_numpy(X):
  return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12, 0, 1]))

array([0.99999386, 0.5       , 0.73105858])

This cell defines a NumPy-optimized sigmoid function `sigmoid_numpy` that can handle array inputs efficiently. It also demonstrates its use with an array of values.

In [46]:
class myNN:
  def __init__(self):
    self.w1 = 1
    self.w2 = 1
    self.bias = 0


  def fit(self, X, y, epochs, loss_threshold):
    self.w1, self.w2, self.bias = self.gradient_descent(X['age'], X['affordability'], y, epochs, loss_threshold)

  def predict(self, X_test):
    weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordability'] + self.bias
    return sigmoid_numpy(weighted_sum)

  def gradient_descent(self, age, affordability, y_true, epochs, loss_threshold):
    # w1, w2, bias
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age) #  len of samples

    for i in range(epochs):

      weighted_sum = w1 * age + w2 * affordability + bias

      y_predicted = sigmoid_numpy(weighted_sum)

      loss = log_loss(y_true, y_predicted)

      w1d = (1/n)*np.dot(np.transpose(age), (y_predicted-y_true))
      w2d = (1/n)*np.dot(np.transpose(affordability), (y_predicted-y_true))

      bias_d = np.mean(y_predicted-y_true)

      w1 = w1 - rate * w1d
      w2 = w2 - rate * w2d
      bias = bias - rate * bias_d

      if i%50==0:
        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

      if loss<=loss_threshold:
        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
        break

    return w1, w2, bias


This cell defines a custom neural network class `myNN` from scratch. It includes methods for initialization, fitting the model using gradient descent, and making predictions. The `gradient_descent` method iteratively updates weights and bias to minimize the `log_loss`.

In [52]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=500, loss_threshold=0.3378)

Epoch:0, w1:0.9945110614931334, w2:1.0468713998756745, bias:-0.0592705528275498, loss:0.4772226499220122
Epoch:18, w1:0.9896689236527303, w2:1.8823826156652443, bias:-0.7679528897675861, loss:0.3368231372103393


This cell creates an instance of the `myNN` class and trains it using the `fit` method. It uses the `X_train_scaled` and `y_train` data, runs for up to 500 epochs, but stops early if the loss drops below the specified `loss_threshold` of 0.3378.

In [53]:
coef, intercept

(array([[0.87013274],
        [1.8946897 ]], dtype=float32),
 array([-0.6880684], dtype=float32))

This cell displays the final `coef` (weights) and `intercept` (bias) values learned by the Keras model.

In [54]:
customModel.predict(X_test_scaled)

,0
36,0.851677
46,0.824897
7,0.819105
41,0.831930
17,0.833309
14,0.822020
34,0.361232
33,0.827738
45,0.808613
39,0.834679


This cell uses the custom `myNN` model to make predictions on the `X_test_scaled` data, providing an alternative to the Keras model's predictions.

In [55]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[0.85364825],
       [0.83054286],
       [0.8255878 ],
       [0.8365783 ],
       [0.83776444],
       [0.82807946],
       [0.3742465 ],
       [0.83297807],
       [0.8166427 ],
       [0.8389436 ]], dtype=float32)

This cell re-runs the Keras model's prediction on the `X_test_scaled` data, likely for comparison with the custom model's predictions.